[package]
name = "eight-bit-beats"
version = "0.0.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
cpal = "0.15.3"
dasp_signal = "0.11.0"
ratatui = "0.29.0"
rodio = "0.20.1"
rust-music-theory = "0.2.0"
serde = "1.0.217"
serde_json = "1.0.138"
rand = "0.9.0"
